# Generated by Django 3.1.7 on 2021-03-03 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0005_auto_20210303_0705'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='organisation',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='leave.userprofile'),
            preserve_default=False,
        ),
    ]
